//package com.aws.dynamodb.entity;
//
//
//import lombok.Data;
//import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
//
//@DynamoDbBean(converterProviders = "Product") // This must be the same as in DynamoDB
//@Data
//public class Product {
//    @DynamoDBHashKey(attributeName = "id")
//    @DynamoDBAutoGeneratedKey  
//    private String id;
//
//    @DynamoDBAttribute
//    private String name;
//
//    @DynamoDBAttribute
//    private double price;
//
//    @DynamoDBAttribute
//    private Long stockCount;
//
//}